name: .Net Project

on:
    pull_request:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-24.04

        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-dotnet@v4
            with:
              dotnet-version: '9'
        #   - name: Restore dependencies
        #     run: dotnet restore

          - name: Build
            run: dotnet build nop