name: starter pipeline

on:
    pull_request:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - uses: action/chekcout@develop
            - name: Set-up JDK 17
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'
                cache: 'maven'
            - name: Maven Clean Package
              run: mvn clean package
